/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.util.Random;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import static paquete.ConvolucionFinita.getArray;
import static paquete.ConvolucionFinita.llenaMatrizGeneral;
import static paquete.ConvolucionFinita.llenaMatrizUnitaria;
import static paquete.ConvolucionFinita.multiplicarMatrices;
import static paquete.ConvolucionFinita.origenFinal;

/**
 *
 * @author csb
 */
public class Convolucion extends javax.swing.JFrame {

    /**
     * Creates new form Convolucion
     */
        public static String salida;

    
    
    public Convolucion() {
        
        salida = "<html>";
        initComponents();
        this.setVisible(true);
        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConvo = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        arreglo2Convolucion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        arreglo1Convolucion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        convolucionBoton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        textoSalida = new javax.swing.JLabel();


        panelConvo.setBackground(new java.awt.Color(48, 63, 159));
        panelConvo.setSize(new java.awt.Dimension(683, 552));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Convolución");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Primer arreglo");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Segundo arreglo");

        convolucionBoton.setText("Convolución!");
        convolucionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convolucionBotonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(48, 63, 159));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.setAutoscrolls(true);

        textoSalida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textoSalida.setForeground(new java.awt.Color(255, 255, 255));
        textoSalida.setText("Presiona el botón de convolución");
        textoSalida.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoSalida)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelConvoLayout = new javax.swing.GroupLayout(panelConvo);
        panelConvo.setLayout(panelConvoLayout);
        panelConvoLayout.setHorizontalGroup(
            panelConvoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConvoLayout.createSequentialGroup()
                .addGroup(panelConvoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConvoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelConvoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arreglo2Convolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(arreglo1Convolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(convolucionBoton))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConvoLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel11)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelConvoLayout.setVerticalGroup(
            panelConvoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConvoLayout.createSequentialGroup()
                .addGroup(panelConvoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConvoLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(arreglo1Convolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(arreglo2Convolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(convolucionBoton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelConvoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConvo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConvo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convolucionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convolucionBotonActionPerformed

        //Obtener los elementos de los input
        String input1 = arreglo1Convolucion.getText();
        String input2 = arreglo2Convolucion.getText();
        
        //Añadir a los arreglos
        
        String[] arreglo1String = input1.split("");
        String[] arreglo2String = input2.split("");
        
        double[] arreglo1 = new double[input1.length()];
        double[] arreglo2 = new double[input2.length()];
        
                
            //Input 1
            for (int i=0; i<arreglo1String.length; i++){
                arreglo1[i] = Double.parseDouble(arreglo1String[i]);
            }
            
            //Input 2
            for (int i=0; i<arreglo2String.length; i++){
                arreglo2[i] = Double.parseDouble(arreglo2String[i]);
            }        
            
        
        int tam = arreglo1.length + arreglo2.length -1;
        double[][] matrizGeneral = new double[tam][tam];
        double[][] matrizUnitaria = new double[tam][1];
        llenaMatrizGeneral(arreglo1,matrizGeneral,tam);
        llenaMatrizUnitaria(arreglo2,matrizUnitaria,tam);
        multiplicarMatrices(matrizGeneral,matrizUnitaria);


        salida+="</html>";
        textoSalida.setText(salida);
        salida = "<html>";
    }//GEN-LAST:event_convolucionBotonActionPerformed


    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convolucion().setVisible(true);
            }
        });
    }

    
    //Funciones de la convolucion

    public static void llenaMatrizGeneral(double[] valores, double[][] matriz, int tam){
        for (int i=0; i < tam; i++) {
            for (int j = 0; j < tam; j++) {
                matriz[i][j] = 0;
            }
        }
        for (int i=0; i < valores.length; i++) {
            for (int j = 0; j < tam; j++) {
                matriz[(i+j)%tam][j] = valores[i];
            }
        }
        salida += "Matriz Cuadrada<br>";
        imprimirMatriz(matriz, "Matriz Cuadrada");
    }
    public static void imprimirMatriz(double [][]a, String titulo){
        //System.out.println("<------------------->");
        //System.out.println("<--"+titulo+"-->");
        //System.out.println("<------------------->");
        for (int i=0; i < a.length; i++) {
            for (int j = 0; j < a[0].length; j++) {
                System.out.print(a[i][j]+",");
                salida += a[i][j]+",";
            }System.out.println("");
            salida += "<br>";
        }
    }
    public static void llenaMatrizUnitaria(double[] valores, double[][] matriz, int tam){
        for (int i=0; i < tam; i++) {
            matriz[i][0] = 0; 
        }
        for (int i=0; i < valores.length; i++) {
            matriz[(i+0)%tam][0] = valores[i];
        }
        
        salida += "<br>Matriz Unitaria<br>";
        imprimirMatriz(matriz, "Matriz Unitaria");
        
    }
    
    public static void multiplicarMatrices(double [][]a, double [][]b){
        double [][] aux = new double[a.length][b[0].length];
        for (int i = 0; i < a.length; i++) {
            for (int j = 0; j < b[0].length; j++) {
                aux[i][j] =0;
                for (int k = 0; k < b.length; k++) {                    
                    aux[i][j] += a[i][k] * b[k][j];
                }
            }
        }
        salida+="<br>Resultado Final<br>";
        imprimirMatriz(aux, "Resultado Final");
        
        salida+="El origen final: Valor[";
        salida+=(origenFinal+1)+"]=";
        salida+= aux[origenFinal][0];
        System.out.println("<br>El origen final: Valor["+(origenFinal+1)+"]="+aux[origenFinal][0]);
        
    }
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arreglo1Convolucion;
    private javax.swing.JTextField arreglo2Convolucion;
    private javax.swing.JButton convolucionBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelConvo;
    private javax.swing.JLabel textoSalida;
    // End of variables declaration//GEN-END:variables
}
