/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import static Ventanas.InicioGrabar.data;
import static Ventanas.InicioGrabar.datan;
import static Ventanas.InicioGrabar.ob;
import javax.swing.JFrame;
import paquete.JFrameVentana;
import paquete.OperacionesBasicas;
import paquete.ReadSound;

/**
 *
 * @author csb
 */
public class Interpolacion extends javax.swing.JFrame {

    ReadSound rds;
    int segundos;

    public Interpolacion(double[] data) {
        initComponents();
        this.setVisible(true);
        Ventanas.InicioGrabar.data = data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        atenuarK2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        interpolacionCero = new javax.swing.JButton();
        interpolacionLineal = new javax.swing.JButton();
        interpolacionEscalon = new javax.swing.JButton();
        ceroK = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        escalonK = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        linealK = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        reproducirEntrada3 = new javax.swing.JButton();
        reproducirSalida = new javax.swing.JButton();
        reproducirSalida1 = new javax.swing.JButton();

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("K =");

        atenuarK2.setText("5");
        atenuarK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenuarK2ActionPerformed(evt);
            }
        });

        setTitle("Interpolación");

        jPanel1.setBackground(new java.awt.Color(48, 63, 159));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Interpolación");

        jPanel3.setBackground(new java.awt.Color(48, 63, 159));

        interpolacionCero.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        interpolacionCero.setText("Interpolación a Cero");
        interpolacionCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpolacionCeroActionPerformed(evt);
            }
        });

        interpolacionLineal.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        interpolacionLineal.setText("Interpolación Lineal");
        interpolacionLineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpolacionLinealActionPerformed(evt);
            }
        });

        interpolacionEscalon.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        interpolacionEscalon.setText("Interpolación escalón");
        interpolacionEscalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interpolacionEscalonActionPerformed(evt);
            }
        });

        ceroK.setText("5");
        ceroK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroKActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("K =");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("K =");

        escalonK.setText("5");
        escalonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalonKActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("K =");

        linealK.setText("5");
        linealK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linealKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(interpolacionCero, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(interpolacionEscalon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(interpolacionLineal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ceroK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escalonK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linealK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ceroK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(escalonK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(linealK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interpolacionCero)
                    .addComponent(interpolacionLineal)
                    .addComponent(interpolacionEscalon))
                .addGap(26, 26, 26))
        );

        jPanel4.setBackground(new java.awt.Color(48, 63, 159));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        reproducirEntrada3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        reproducirEntrada3.setText("Reproducir Entrada");
        reproducirEntrada3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproducirEntrada3ActionPerformed(evt);
            }
        });

        reproducirSalida.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        reproducirSalida.setText("Reproducir Salida");
        reproducirSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproducirSalidaActionPerformed(evt);
            }
        });

        reproducirSalida1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        reproducirSalida1.setText("Gráficar");
        reproducirSalida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproducirSalida1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reproducirEntrada3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(reproducirSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(reproducirSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reproducirEntrada3)
                    .addComponent(reproducirSalida)
                    .addComponent(reproducirSalida1))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void interpolacionEscalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpolacionEscalonActionPerformed
        int k =Integer.parseInt(escalonK.getText());
        datan = ob.interpolacionEscalon(data, k);
        if (datan == null) {
            System.out.println("PARA REPRODUCIR TIENES QUE REALIZAR UNA OPERACION");
        } else {
            rds.play("NuevaGrabacion.wav");
        }
    }//GEN-LAST:event_interpolacionEscalonActionPerformed

    private void interpolacionLinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpolacionLinealActionPerformed
        int k =Integer.parseInt(linealK.getText());
        datan = ob.interpolacionLineal(data, k);
        if (datan == null) {
            System.out.println("PARA REPRODUCIR TIENES QUE REALIZAR UNA OPERACION");
        } else {
            rds.play("NuevaGrabacion.wav");
        }
    }//GEN-LAST:event_interpolacionLinealActionPerformed

    private void interpolacionCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interpolacionCeroActionPerformed
        int k =Integer.parseInt(ceroK.getText());
        datan = ob.interpolacionCero(data, k);
        if (datan == null) {
            System.out.println("PARA REPRODUCIR TIENES QUE REALIZAR UNA OPERACION");
        } else {
            rds.play("NuevaGrabacion.wav");
        }
    }//GEN-LAST:event_interpolacionCeroActionPerformed

    private void ceroKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceroKActionPerformed

    private void escalonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalonKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escalonKActionPerformed

    private void atenuarK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenuarK2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atenuarK2ActionPerformed

    private void linealKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linealKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linealKActionPerformed

    private void reproducirEntrada3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproducirEntrada3ActionPerformed
        rds.play("Grabacion.wav");
    }//GEN-LAST:event_reproducirEntrada3ActionPerformed

    private void reproducirSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproducirSalidaActionPerformed
        if (datan == null) {
            System.out.println("PARA REPRODUCIR TIENES QUE REALIZAR UNA OPERACION");
        } else {
            rds.play("NuevaGrabacion.wav");
        }
    }//GEN-LAST:event_reproducirSalidaActionPerformed

    private void reproducirSalida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproducirSalida1ActionPerformed
        JFrameVentana newv = new JFrameVentana();
        newv.setVisible(true);
    }//GEN-LAST:event_reproducirSalida1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amplificarK;
    private javax.swing.JTextField amplificarK1;
    private javax.swing.JTextField atenuarK2;
    private javax.swing.JTextField ceroK;
    private javax.swing.JTextField escalonK;
    private javax.swing.JButton interpolacionCero;
    private javax.swing.JButton interpolacionEscalon;
    private javax.swing.JButton interpolacionLineal;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField linealK;
    private javax.swing.JButton reproducirEntrada3;
    private javax.swing.JButton reproducirSalida;
    private javax.swing.JButton reproducirSalida1;
    // End of variables declaration//GEN-END:variables
}
